name: hannah says hello photography
favicon: null
layout_spectrum: 0.2850535742472857
typography_spectrum: 0.6404348034411669
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0a08'
    - '#f0f0f2'
    - '#debbbb'
    - '#798b91'
    - '#a14551'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
