name: hannah says hello photography
favicon: null
layout_spectrum: 0.2850535742472857
typography_spectrum: 0.6404348034411669
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9706704271957278
  lightness: 0.12817457877099514
  saturation: 0.24116743332706392
  rhythmicContrast: 0.24311982514336705
purpose: []
